id: I26578E7D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:04:37+00:00'
last_modified: '2022-06-08T03:12:28.199808+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24478
  title: འཁྲུལ་ཞིག་རྡོ་རྗེ་འཆང་གི་བླ་སྒྲུབ་གསོལ་འདེབས་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    64D2:
      image_group_id: I1KG24500
      title: ''
      total_pages: 2108
      order: 1
      base_file: 64D2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
